baseURL = "https://vivirpandemia.netlify.app/"
languageCode = "en-us"
title = "TAREA 01"
theme = "gohugo-theme-ananke"

[menu]
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0