baseURL = " "https://vivirconpandemia.netlify.app/""
languageCode = "en-us"
title = "TAREA 01"
theme = "cupper"

[menu]
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0

